theme: jekyll-theme-cayman
<!DOCTYPE html>
<html>
<head>
<script>
function validateEmail(email) {
    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(String(email).toLowerCase());
}
 function KelimeSayisiBul(kelime) {
        var kelimeler = new Array();
        kelimeler = kelime.split(" ");
        var cnt = kelimeler.length;
		if (cnt==3 && kelimeler[0]!="" &&kelimeler[1]!="" && kelimeler[2]!=""){
		return true;
		}
		else {
		return false;}    
		}
		
function validateForm() {
	var a = document.querySelector("#name").value;
	var b = document.querySelector("#email").value;
	var c = document.querySelector("#sayisal").value;
	var d = document.querySelector("#basamakli").value;
	var e = document.querySelector("#alfa").value;
	var f = document.querySelector("#max30").value;
	var g = document.querySelector("#uckelime").value;
	var h = document.querySelector("#password").value;
	var rakamlar = /^[0-9]+$/;
	var alphaExp = /^[a-zA-Z]+$/;	
	var sayı=/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,}$.g/;
	if (a == "") {	
document.getElementById("a").innerHTML="Boş Olmamalı!";
	}
	if(a!="") {
	document.getElementById("a").innerHTML=" ";	
	}
	 if (!validateEmail(b)) {
		document.getElementById("b").innerHTML="Kurallara uygun email olmalı!";
	}
	 if (!c.match(rakamlar)) {
		document.getElementById("c").innerHTML="Sadece sayısal değer olmalı!";
	}
	 if ((d.toString().length!=12) || !(d.match(rakamlar))) {
		document.getElementById("d").innerHTML="Sadece sayısal olan ve 12 basamak uzunluğundaki sayi olmalı!";
	}
	 if (!e.match(alphaExp)) {
		document.getElementById("e").innerHTML="Sadece harf (a..z veya A..Z) olmalı!";
	}
	 if ( !(f.match(alphaExp) ) || (f.toString().length > 30) ) {
		document.getElementById("f").innerHTML="Sadece harf ve en fazla 30 uzunlukta olan string olmalı!";
    }	
	 if (!KelimeSayisiBul(g)) {
		document.getElementById("g").innerHTML="3 kelimeden oluşan string olmalı!";
    }
	
	   var sifre= document.querySelector("#password").value;
  if(/^(?=.*[\d])(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*.,:;?-])[\w!@#$%^&*.,:;?-]{8,}$/.test(sifre) ==false ) {
    document.getElementById("h").innerHTML="Hatalı Şifre Girdiniz!!";
     
  }
  if(/^(?=.*[\d])(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*.,:;?-])[\w!@#$%^&*.,:;?-]{8,}$/.test(sifre) ==true ){
    document.getElementById("h").innerHTML="";
  }
	 
		 if (validateEmail(b)) {
		document.getElementById("b").innerHTML="";
	}	
	 if (c.match(rakamlar)) {
		document.getElementById("c").innerHTML="";  
	}
	 if ((d.toString().length==12) && (d.match(rakamlar))) {
		document.getElementById("d").innerHTML="";  
	}
	 if (e.match(alphaExp)) {
		document.getElementById("e").innerHTML=" ";   
	}
	 if ( (f.match(alphaExp) ) && (f.toString().length <30) ) {
		document.getElementById("f").innerHTML="";  
    }	
	 if (KelimeSayisiBul(g)) {
		document.getElementById("g").innerHTML="";
    }
	 return false;
}
</script>
</head>
<body>

<form name="myForm" action="/action_page.php" onsubmit="return validateForm()" method="post">
  Aşağıdaki hiçbir input boş olmamalı: <br> 
 
  <table style="width:60%">
    
  <tr>
    <td>Boş olmamalı: </td>
    <td><input type="text" id="name"></td>
      <td id="a" style="color:red;width: 50%">
    </td>
  </tr>
  <tr>
    <td>E-mail (Kurallara uygun email): </td>
    <td><input type="text" id="email"></td>
      <td id="b" style="color:red;width: 50%">
    </td>
  </tr>
  <tr>
    <td>Sadece sayısal: </td>
    <td><input type="text" id="sayisal"></td>
      <td id="c" style="color:red;width: 50%">
    </td>
  </tr>
  <tr>
    <td>Sadece sayısal olan ve 12 basamak uzunluğundaki sayi: </td>
    <td><input type="text" id="basamakli"></td>
     <td id="d" style="color:red;width: 50%">
    </td>
  </tr>
  <tr>
    <td>Sadece harf (a..z veya A..Z): </td>
    <td><input type="text" id="alfa"></td>
      <td id="e" style="color:red;width: 50%">
  </td>
  </tr>
  <tr>
    <td>Sadece harf ve en fazla 30 uzunlukta olan string: </td>
    <td><input type="text" id="max30"></td>
      <td id="f" style="color:red;width: 50%">
    </td>
  </tr>
  <tr>
    <td>3 kelimeden oluşan string: </td>
    <td><input type="text" id="uckelime"></td>
      <td id="g" style="color:red;width: 50%">
    </td>
  </tr>
  <tr>
    <td>En az 1 büyük harf, en az 1 küçük harf, en az bir rakam ve en az 1 noktalama işareti içeren ve en az 8 uzunluğunda olan metin: </td>
    <td><input type="text" id="password"></td>
      <td id="h" style="color:red;width: 50%">
    </td>
  </tr>
  
</table>

<br>
  <input type="submit" value="Submit" id="buton">
</form>

</body>
</html>
